import tailwindForms from '@tailwindcss/forms';
import tailwindContainerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: "#ffb4ab",
        "surface-container-low": "#0f1c2c",
        "surface-container": "#132030",
        "primary-fixed": "#d1e4ff",
        "tertiary-container": "#4d586f",
        "tertiary-fixed": "#d7e2ff",
        secondary: "#b2c8e7",
        "secondary-container": "#354b64",
        "on-tertiary": "#263046",
        "on-secondary-fixed": "#031d34",
        "on-primary-container": "#b7d1f3",
        "secondary-fixed-dim": "#b2c8e7",
        "secondary-fixed": "#d1e4ff",
        "surface-container-highest": "#283646",
        "on-background": "#d6e4f9",
        "on-primary": "#17324d",
        "on-tertiary-container": "#c4cfea",
        "inverse-on-surface": "#243141",
        "on-secondary": "#1b324a",
        "outline-variant": "#43474d",
        "surface-bright": "#2d3a4a",
        "inverse-primary": "#47607e",
        "on-secondary-container": "#a4bad8",
        "on-error": "#690005",
        "inverse-surface": "#d6e4f9",
        "tertiary-fixed-dim": "#bbc6e2",
        "on-tertiary-fixed-variant": "#3c475d",
        surface: "#061423",
        "on-tertiary-fixed": "#101b30",
        "surface-container-high": "#1e2b3b",
        "on-primary-fixed": "#001d36",
        "on-surface": "#d6e4f9",
        "primary-container": "#415a77",
        primary: "#afc9ea",
        "surface-dim": "#061423",
        "on-primary-fixed-variant": "#2f4865",
        "error-container": "#93000a",
        "primary-fixed-dim": "#afc9ea",
        tertiary: "#bbc6e2",
        "on-secondary-fixed-variant": "#334861",
        background: "#061423",
        "on-surface-variant": "#c3c6ce",
        "on-error-container": "#ffdad6",
        "surface-variant": "#283646",
        "surface-tint": "#afc9ea",
        outline: "#8d9198",
        "surface-container-lowest": "#020f1e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "container-padding": "24px",
        "glass-padding": "20px",
        gutter: "16px",
      },
      fontFamily: {
        "stat-label": ["Space Grotesk", "sans-serif"],
        "title-md": ["Sora", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Sora", "sans-serif"],
        "headline-lg": ["Sora", "sans-serif"],
        "headline-lg-mobile": ["Sora", "sans-serif"],
      },
      fontSize: {
        "stat-label": ["14px", { lineHeight: "1", fontWeight: "500" }],
        "title-md": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
      },
    },
  },
  plugins: [tailwindForms, tailwindContainerQueries],
};