@SkillLink.Api_HostAddress = http://localhost:5082

GET {{SkillLink.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
@SkillLink.Api_HostAddress = http://localhost:5082

GET {{SkillLink.Api_HostAddress}}/weatherforecast/
Accept: application/json

###