// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillLink.Infrastructure.Persistence;

#nullable disable

namespace SkillLink.Infrastructure.Migrations
{
    [DbContext(typeof(SkillLinkDbContext))]
    [Migration("20260711225212_AddTablaTokenRecuperacion")]
    partial class AddTablaTokenRecuperacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillLink.Domain.Entities.Habilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Logro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoCondicion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ValorCondicion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Logros");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Descripcion = "Alcanza 50 XP",
                            Nombre = "Primeros pasos",
                            TipoCondicion = "xp_total",
                            ValorCondicion = 50
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Descripcion = "Alcanza 200 XP",
                            Nombre = "En marcha",
                            TipoCondicion = "xp_total",
                            ValorCondicion = 200
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Descripcion = "Completa 1 misión",
                            Nombre = "Constante",
                            TipoCondicion = "misiones_completadas",
                            ValorCondicion = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Descripcion = "Completa 3 misiones",
                            Nombre = "Comprometido",
                            TipoCondicion = "misiones_completadas",
                            ValorCondicion = 3
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Descripcion = "Alcanza 1000 XP",
                            Nombre = "Maestro del XP",
                            TipoCondicion = "xp_total",
                            ValorCondicion = 1000
                        });
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Mision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("UsuarioAsignadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("XpValor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Misiones");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.NivelConfiguracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("XpMinimo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NivelConfiguraciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nivel = 1,
                            Titulo = "Novato",
                            XpMinimo = 0
                        },
                        new
                        {
                            Id = 2,
                            Nivel = 5,
                            Titulo = "Colaborador",
                            XpMinimo = 400
                        },
                        new
                        {
                            Id = 3,
                            Nivel = 10,
                            Titulo = "Estratega",
                            XpMinimo = 900
                        },
                        new
                        {
                            Id = 4,
                            Nivel = 20,
                            Titulo = "Líder",
                            XpMinimo = 1900
                        },
                        new
                        {
                            Id = 5,
                            Nivel = 30,
                            Titulo = "Maestro",
                            XpMinimo = 2900
                        });
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.TokenRecuperacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Usado")
                        .HasColumnType("bit");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("TokensRecuperacion");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Carrera")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.UsuarioHabilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HabilidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HabilidadId");

                    b.HasIndex("UsuarioId", "HabilidadId")
                        .IsUnique();

                    b.ToTable("UsuarioHabilidades");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.UsuarioLogro", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LogroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaObtenido")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "LogroId");

                    b.HasIndex("LogroId");

                    b.ToTable("UsuarioLogros");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.TokenRecuperacion", b =>
                {
                    b.HasOne("SkillLink.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.UsuarioHabilidad", b =>
                {
                    b.HasOne("SkillLink.Domain.Entities.Habilidad", "Habilidad")
                        .WithMany()
                        .HasForeignKey("HabilidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillLink.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.UsuarioLogro", b =>
                {
                    b.HasOne("SkillLink.Domain.Entities.Logro", "Logro")
                        .WithMany()
                        .HasForeignKey("LogroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logro");
                });
#pragma warning restore 612, 618
        }
    }
}
