// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillLink.Infrastructure.Persistence;

#nullable disable

namespace SkillLink.Infrastructure.Migrations
{
    [DbContext(typeof(SkillLinkDbContext))]
    [Migration("20260812083114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkillLink.Domain.Entities.ActividadReciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Fecha");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Equipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Habilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.InvitacionEquipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioInvitaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioInvitadoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("UsuarioInvitaId");

                    b.HasIndex("UsuarioInvitadoId");

                    b.ToTable("InvitacionesEquipo");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Logro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoCondicion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ValorCondicion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Logros");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Descripcion = "Alcanza 50 XP.",
                            Nombre = "Primeros pasos",
                            TipoCondicion = "xp_total",
                            ValorCondicion = 50
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Descripcion = "Alcanza 100 XP.",
                            Nombre = "Aprendiz",
                            TipoCondicion = "xp_total",
                            ValorCondicion = 100
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Descripcion = "Alcanza 250 XP.",
                            Nombre = "Colaborador",
                            TipoCondicion = "xp_total",
                            ValorCondicion = 250
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Descripcion = "Alcanza 500 XP.",
                            Nombre = "Experto",
                            TipoCondicion = "xp_total",
                            ValorCondicion = 500
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Descripcion = "Alcanza 1000 XP.",
                            Nombre = "Maestro del equipo",
                            TipoCondicion = "xp_total",
                            ValorCondicion = 1000
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Descripcion = "Completa tu primera misión.",
                            Nombre = "Recién llegado",
                            TipoCondicion = "misiones_completadas",
                            ValorCondicion = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Descripcion = "Completa 5 misiones.",
                            Nombre = "En marcha",
                            TipoCondicion = "misiones_completadas",
                            ValorCondicion = 5
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Descripcion = "Completa 10 misiones.",
                            Nombre = "Misionero",
                            TipoCondicion = "misiones_completadas",
                            ValorCondicion = 10
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Descripcion = "Completa 25 misiones.",
                            Nombre = "Especialista en misiones",
                            TipoCondicion = "misiones_completadas",
                            ValorCondicion = 25
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Descripcion = "Completa 50 misiones.",
                            Nombre = "Leyenda de las misiones",
                            TipoCondicion = "misiones_completadas",
                            ValorCondicion = 50
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Descripcion = "Crea tu primer proyecto.",
                            Nombre = "Primer proyecto",
                            TipoCondicion = "proyectos_creados",
                            ValorCondicion = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Descripcion = "Crea 3 proyectos.",
                            Nombre = "Constructor",
                            TipoCondicion = "proyectos_creados",
                            ValorCondicion = 3
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Descripcion = "Crea 5 proyectos.",
                            Nombre = "Creador de proyectos",
                            TipoCondicion = "proyectos_creados",
                            ValorCondicion = 5
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Descripcion = "Crea 10 proyectos.",
                            Nombre = "Gestor de proyectos",
                            TipoCondicion = "proyectos_creados",
                            ValorCondicion = 10
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Descripcion = "Crea 20 proyectos.",
                            Nombre = "Arquitecto",
                            TipoCondicion = "proyectos_creados",
                            ValorCondicion = 20
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Descripcion = "Crea tu primer equipo.",
                            Nombre = "Fundador",
                            TipoCondicion = "equipos_creados",
                            ValorCondicion = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Descripcion = "Crea 3 equipos.",
                            Nombre = "Organizador",
                            TipoCondicion = "equipos_creados",
                            ValorCondicion = 3
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Descripcion = "Crea 5 equipos.",
                            Nombre = "Líder de equipos",
                            TipoCondicion = "equipos_creados",
                            ValorCondicion = 5
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            Descripcion = "Crea 10 equipos.",
                            Nombre = "Coordinador",
                            TipoCondicion = "equipos_creados",
                            ValorCondicion = 10
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            Descripcion = "Crea 20 equipos.",
                            Nombre = "Líder nato",
                            TipoCondicion = "equipos_creados",
                            ValorCondicion = 20
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Descripcion = "Registra tu primera habilidad.",
                            Nombre = "Primera habilidad",
                            TipoCondicion = "habilidades_registradas",
                            ValorCondicion = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Descripcion = "Registra 3 habilidades.",
                            Nombre = "Multitalento",
                            TipoCondicion = "habilidades_registradas",
                            ValorCondicion = 3
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Descripcion = "Registra 5 habilidades.",
                            Nombre = "Versátil",
                            TipoCondicion = "habilidades_registradas",
                            ValorCondicion = 5
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            Descripcion = "Registra 8 habilidades.",
                            Nombre = "Especialista",
                            TipoCondicion = "habilidades_registradas",
                            ValorCondicion = 8
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            Descripcion = "Registra 12 habilidades.",
                            Nombre = "Polímata",
                            TipoCondicion = "habilidades_registradas",
                            ValorCondicion = 12
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            Descripcion = "Envía tu primer mensaje.",
                            Nombre = "Hola equipo",
                            TipoCondicion = "mensajes_enviados",
                            ValorCondicion = 1
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            Descripcion = "Envía 10 mensajes.",
                            Nombre = "Comunicador",
                            TipoCondicion = "mensajes_enviados",
                            ValorCondicion = 10
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            Descripcion = "Envía 50 mensajes.",
                            Nombre = "Conversador",
                            TipoCondicion = "mensajes_enviados",
                            ValorCondicion = 50
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            Descripcion = "Envía 100 mensajes.",
                            Nombre = "Comunicador experto",
                            TipoCondicion = "mensajes_enviados",
                            ValorCondicion = 100
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000005"),
                            Descripcion = "Envía 250 mensajes.",
                            Nombre = "Maestro de la comunicación",
                            TipoCondicion = "mensajes_enviados",
                            ValorCondicion = 250
                        });
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Mensaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EmisorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmisorId");

                    b.HasIndex("EquipoId", "Fecha");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.MensajePrivado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EmisorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leido")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ReceptorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReceptorId");

                    b.HasIndex("EmisorId", "ReceptorId", "Fecha");

                    b.ToTable("MensajesPrivados");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.MiembroEquipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EquipoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("MiembrosEquipo");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Mision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<Guid?>("EquipoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsUrgente")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Etiquetas")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Progreso")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProyectoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("UsuarioAsignadoId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpValor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Misiones");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.NivelConfiguracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("XpMinimo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("NivelConfiguraciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nivel = 1,
                            Titulo = "Novato",
                            XpMinimo = 0
                        },
                        new
                        {
                            Id = 2,
                            Nivel = 5,
                            Titulo = "Colaborador",
                            XpMinimo = 400
                        },
                        new
                        {
                            Id = 3,
                            Nivel = 10,
                            Titulo = "Estratega",
                            XpMinimo = 900
                        },
                        new
                        {
                            Id = 4,
                            Nivel = 20,
                            Titulo = "Líder",
                            XpMinimo = 1900
                        },
                        new
                        {
                            Id = 5,
                            Nivel = 30,
                            Titulo = "Maestro",
                            XpMinimo = 2900
                        });
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Leida");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Proyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.TokenRecuperacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("TokensRecuperacion");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Carrera")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Foto")
                        .HasColumnType("text");

                    b.Property<string>("Github")
                        .HasColumnType("text");

                    b.Property<string>("Linkedin")
                        .HasColumnType("text");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RachaActual")
                        .HasColumnType("integer");

                    b.Property<int?>("Semestre")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimaActividad")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimoXpMensajeFecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.UsuarioHabilidad", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HabilidadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UsuarioId", "HabilidadId");

                    b.HasIndex("HabilidadId");

                    b.ToTable("UsuarioHabilidades", (string)null);
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.UsuarioLogro", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LogroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaObtenido")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UsuarioId", "LogroId");

                    b.HasIndex("LogroId");

                    b.ToTable("UsuarioLogros");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.InvitacionEquipo", b =>
                {
                    b.HasOne("SkillLink.Domain.Entities.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillLink.Domain.Entities.Usuario", "UsuarioInvita")
                        .WithMany()
                        .HasForeignKey("UsuarioInvitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillLink.Domain.Entities.Usuario", "UsuarioInvitado")
                        .WithMany()
                        .HasForeignKey("UsuarioInvitadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("UsuarioInvita");

                    b.Navigation("UsuarioInvitado");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Mensaje", b =>
                {
                    b.HasOne("SkillLink.Domain.Entities.Usuario", "Emisor")
                        .WithMany()
                        .HasForeignKey("EmisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillLink.Domain.Entities.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emisor");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.MensajePrivado", b =>
                {
                    b.HasOne("SkillLink.Domain.Entities.Usuario", "Emisor")
                        .WithMany()
                        .HasForeignKey("EmisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillLink.Domain.Entities.Usuario", "Receptor")
                        .WithMany()
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emisor");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.MiembroEquipo", b =>
                {
                    b.HasOne("SkillLink.Domain.Entities.Equipo", "Equipo")
                        .WithMany("Miembros")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillLink.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Mision", b =>
                {
                    b.HasOne("SkillLink.Domain.Entities.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId");

                    b.HasOne("SkillLink.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipo");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("SkillLink.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Proyecto", b =>
                {
                    b.HasOne("SkillLink.Domain.Entities.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.PushSubscription", b =>
                {
                    b.HasOne("SkillLink.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.TokenRecuperacion", b =>
                {
                    b.HasOne("SkillLink.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.UsuarioHabilidad", b =>
                {
                    b.HasOne("SkillLink.Domain.Entities.Habilidad", "Habilidad")
                        .WithMany()
                        .HasForeignKey("HabilidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillLink.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioHabilidades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.UsuarioLogro", b =>
                {
                    b.HasOne("SkillLink.Domain.Entities.Logro", "Logro")
                        .WithMany()
                        .HasForeignKey("LogroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logro");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Equipo", b =>
                {
                    b.Navigation("Miembros");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioHabilidades");
                });
#pragma warning restore 612, 618
        }
    }
}
