// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillLink.Infrastructure.Persistence;

#nullable disable

namespace SkillLink.Infrastructure.Migrations
{
    [DbContext(typeof(SkillLinkDbContext))]
    [Migration("20260709024659_AddTablaMision")]
    partial class AddTablaMision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillLink.Domain.Entities.Mision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("UsuarioAsignadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("XpValor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Misiones");
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.NivelConfiguracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("XpMinimo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NivelConfiguraciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nivel = 1,
                            Titulo = "Novato",
                            XpMinimo = 0
                        },
                        new
                        {
                            Id = 2,
                            Nivel = 5,
                            Titulo = "Colaborador",
                            XpMinimo = 400
                        },
                        new
                        {
                            Id = 3,
                            Nivel = 10,
                            Titulo = "Estratega",
                            XpMinimo = 900
                        },
                        new
                        {
                            Id = 4,
                            Nivel = 20,
                            Titulo = "Líder",
                            XpMinimo = 1900
                        },
                        new
                        {
                            Id = 5,
                            Nivel = 30,
                            Titulo = "Maestro",
                            XpMinimo = 2900
                        });
                });

            modelBuilder.Entity("SkillLink.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Carrera")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
